<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-03-08 06:14

from django.db import migrations, models
=======
# Generated by Django 3.1.5 on 2021-03-22 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 6398115 (yes)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 6398115 (yes)
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('catageory', models.CharField(max_length=10)),
                ('subcatageory', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='static/img')),
                ('quentity', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=10)),
                ('longDescription', models.CharField(max_length=1000)),
=======
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('catageory', models.CharField(max_length=30)),
                ('subCatageory', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='static/img')),
                ('quentity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=10)),
                ('longDescription', models.CharField(max_length=1000)),
                ('rating', models.FloatField(default='0')),
                ('offer', models.BooleanField(default=False)),
                ('warrenty', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(default=0)),
                ('seller', models.ForeignKey(default='root', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='myapp.products')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('full_name', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=10)),
                ('zipcode', models.IntegerField()),
                ('note', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 6398115 (yes)
            ],
        ),
    ]
